# Generated by Django 5.1 on 2024-08-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncedPUResults',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('polling_unit_uniqueid', models.IntegerField()),
                ('party_abbreviation', models.CharField(max_length=255)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=255)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 'announced_pu_results',
            },
        ),
    ]
